#!/bin/bash
#
# Copyright 2013 Jarek Jarcec Cecho <jarcec@apache.org>
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This script have two roles
#
# 1) Ensure that we have latest varsion (from git)
# 2) Load the tools into $PATH variable

# Current working directory
pwd=`pwd`

# Directory of this script
dir=`dirname $0`

# File with last update date
last=$dir/last_update

# Current date
date=`date +%Y-%m-%d`

# Update git repository
# We are expecting no local changes, thus the pull instead of fetch
function update() {
  echo "Updating Jarcec's command line tools"
  cd $dir
  git pull
  echo $date > $last
}

# For the case we never run update, run it now
if [[  ! -f $last ]]; then
  update
# For now, call the update once a day
elif [[ `cat $last` < `date +%Y-%m-%d` ]]; then
  update
fi

# Finally put all the tools into the path
export PATH="$PATH:$dir"

# Return to original working directory
cd $pwd
