#!/bin/bash
#
# Copyright 2013 Jarek Jarcec Cecho <jarcec@apache.org>
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script will generate various statistics about source code in given
# repositories. It's currently limited to number of files and code lines
# of few programming languages.
#
# Usage:
#   code-stats <directory> [<directory>, ...]
#
# Example:
#   code-stats sqoop flume

# Global variables for totals
total_files=0
total_lines=0

# Generate overall report for one directory
function overall() {
  dir=$1
  echo "Report for directory: $dir"

  total_files=0
  total_lines=0

  language $dir "Java"    "*.java"
  language $dir "Thrift"  "*.thrift"
  language $dir "Shell"   "*.sh"
  
  echo "Total => Files: $total_files, Lines: $total_lines"
  echo ""
}


# Generate stats - number of java files and source code lines
function language() {
  dir=$1
  name=$2
  filenames=$3

  files=0
  lines=0
  for f in `find $dir -iname "$filenames"`; do
    # Add new file
    files=`expr $files + 1`

    # Calculate number of lines in the file
    tmp=`wc -l $f | cut -f1 -d" "`
    lines=`expr $lines + $tmp`
  done

  # Persist globals
  total_files=`expr $total_files + $files`
  total_lines=`expr $total_lines + $lines`

  echo "  $name => Files: $files, Lines: $lines"
}

# Iterate over all directories specified on the command line
for dir in "$@"; do
  overall $dir
done

