#!/bin/bash
#
# Copyright 2013 Jarek Jarcec Cecho <jarcec@apache.org>
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Usage: find-and-open <regexp>
#
# Search resursively current working directory for files that satisfy
# given regular expression. If there is only one file that satisfes the 
# regexp, we wil open it directly in $EDITOR. Otherwise we will print
# out all found files and offer user the ability to choose what file
# should be opened.

# Regular expression given by user
regexp=$1
if [[ $regexp == "" ]]; then
  echo "Missing regular expression."
  exit 1
fi

# Array where we will store all the files
options=()

# Let's find all available files
i=0
for opt in `find . -iname $regexp`; do
  options[$i]=$opt
  i=`expr $i + 1`
done

# If there is only one file, open it
if [[ ${#options[*]} -eq 0 ]]; then
  echo "Found no files matching '$regexp'"
  exit 0
fi

# If there is only one file, open it
if [[ ${#options[*]} -eq 1 ]]; then
  echo "Opening file: ${options[$index]}"
  exec $EDITOR ${options[0]}
fi

# If there are multiple options, let user choose
echo "Found multiple files: ${#options[*]}"
i=0
for opt in ${options[*]}; do
  echo -e "$i \t $opt"
  i=`expr $i + 1`
done

echo -ne "Open: "
read index

exec $EDITOR ${options[$index]}
